export const APP_LOGIN_ATTEMPT = 'USER_LOGIN_ATTEMPT';

export const APP_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export const APP_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';

export const APP_LOGOUT = 'USER_LOGOUT';